// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: issues.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Section   string `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	Course    string `protobuf:"bytes,4,opt,name=course,proto3" json:"course,omitempty"`
	Professor string `protobuf:"bytes,5,opt,name=professor,proto3" json:"professor,omitempty"`
	Year      int32  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_issues_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Student) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Student) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Student) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *Student) GetProfessor() string {
	if x != nil {
		return x.Professor
	}
	return ""
}

func (x *Student) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FaultyComponent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fixed    bool   `protobuf:"varint,2,opt,name=fixed,proto3" json:"fixed,omitempty"`
	ParentId int64  `protobuf:"varint,3,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Id       int64  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FaultyComponent) Reset() {
	*x = FaultyComponent{}
	mi := &file_issues_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultyComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultyComponent) ProtoMessage() {}

func (x *FaultyComponent) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultyComponent.ProtoReflect.Descriptor instead.
func (*FaultyComponent) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{1}
}

func (x *FaultyComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FaultyComponent) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *FaultyComponent) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FaultyComponent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Issue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Student          *Student           `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	LabRoom          string             `protobuf:"bytes,2,opt,name=labRoom,proto3" json:"labRoom,omitempty"`
	Concern          string             `protobuf:"bytes,3,opt,name=concern,proto3" json:"concern,omitempty"`
	Timestamp        string             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PcNumber         int32              `protobuf:"varint,5,opt,name=pcNumber,proto3" json:"pcNumber,omitempty"`
	Id               int64              `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	FaultyComponents []*FaultyComponent `protobuf:"bytes,7,rep,name=faultyComponents,proto3" json:"faultyComponents,omitempty"`
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_issues_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{2}
}

func (x *Issue) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *Issue) GetLabRoom() string {
	if x != nil {
		return x.LabRoom
	}
	return ""
}

func (x *Issue) GetConcern() string {
	if x != nil {
		return x.Concern
	}
	return ""
}

func (x *Issue) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Issue) GetPcNumber() int32 {
	if x != nil {
		return x.PcNumber
	}
	return 0
}

func (x *Issue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Issue) GetFaultyComponents() []*FaultyComponent {
	if x != nil {
		return x.FaultyComponents
	}
	return nil
}

type IssueList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issues []*Issue `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
}

func (x *IssueList) Reset() {
	*x = IssueList{}
	mi := &file_issues_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueList) ProtoMessage() {}

func (x *IssueList) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueList.ProtoReflect.Descriptor instead.
func (*IssueList) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{3}
}

func (x *IssueList) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

var File_issues_proto protoreflect.FileDescriptor

var file_issues_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x67,
	0x0a, 0x0f, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x78, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x69, 0x78, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf1, 0x01, 0x0a, 0x05, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x12, 0x27, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x52, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61,
	0x62, 0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x62,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x41, 0x0a, 0x10, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x79,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x10, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x30, 0x0a, 0x09, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_issues_proto_rawDescOnce sync.Once
	file_issues_proto_rawDescData = file_issues_proto_rawDesc
)

func file_issues_proto_rawDescGZIP() []byte {
	file_issues_proto_rawDescOnce.Do(func() {
		file_issues_proto_rawDescData = protoimpl.X.CompressGZIP(file_issues_proto_rawDescData)
	})
	return file_issues_proto_rawDescData
}

var file_issues_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_issues_proto_goTypes = []any{
	(*Student)(nil),         // 0: main.Student
	(*FaultyComponent)(nil), // 1: main.FaultyComponent
	(*Issue)(nil),           // 2: main.Issue
	(*IssueList)(nil),       // 3: main.IssueList
}
var file_issues_proto_depIdxs = []int32{
	0, // 0: main.Issue.student:type_name -> main.Student
	1, // 1: main.Issue.faultyComponents:type_name -> main.FaultyComponent
	2, // 2: main.IssueList.issues:type_name -> main.Issue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_issues_proto_init() }
func file_issues_proto_init() {
	if File_issues_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_issues_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_issues_proto_goTypes,
		DependencyIndexes: file_issues_proto_depIdxs,
		MessageInfos:      file_issues_proto_msgTypes,
	}.Build()
	File_issues_proto = out.File
	file_issues_proto_rawDesc = nil
	file_issues_proto_goTypes = nil
	file_issues_proto_depIdxs = nil
}
